services:
  redpanda:
    image: redpandadata/redpanda:v24.1.1
    container_name: laminar-redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=512M
      - --overprovisioned
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr=internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr=internal://redpanda:8082,external://localhost:18082
      - --mode=dev-container
    ports:
      - "19092:19092"
      - "18082:18082"
      - "9644:9644"

  postgres:
    image: postgres:16
    container_name: laminar-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: ${LAMINAR_PG_USER:-laminar}
      POSTGRES_PASSWORD: ${LAMINAR_PG_PASSWORD:-laminar}
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=4
      - -c
      - max_wal_senders=4
    volumes:
      - ./sql/init-cdc.sql:/docker-entrypoint-initdb.d/01-init.sql
